In [1]:
import numpy as np

In [2]:
def GrayСode(BinLen=32):
    return np.random.randint(2, size=BinLen)

In [3]:
def GrayToBinar(bit_string):
    """
    Правило перевода из кода Грея в позиционный код: каждый разряд в позиционном
    коде равен сумме по модулю два этого и всех старших разрядов в коде Грея
    """
    return [sum(bit_string[:i]) % 2 for i in range(len(bit_string),0,-1)][::-1]

In [4]:
def BinaryToInt(bit_string):
    """
    """
    return sum([int(x) * 2 ** y for x, y in zip(list(bit_string), range(len(bit_string) - 1, -1, -1))])

In [5]:
class Decode:
    """
    Полный цикл декодирования: Грей -> двоичный -> целое -> нецелое
    """
    def __init__(self,a,b,bit_string):
        self.A = a
        self.B = b
        self.BitString = bit_string
        self.k = 2**len(bit_string) - 1 
        self.h = (b - a)/(self.k - 1)
    
    def decode(self):
        binary_srting = GrayToBinar(self.BitString)
        #print('binary: ',binary_srting)
        integer = BinaryToInt(binary_srting)
        #print('integer: ',integer)
        if integer == 0:
            return self.A
        elif integer == self.k:
            return self.B
        else:
            return ((self.A + (integer - 1)*self.h + (self.A+integer*self.h)))/2

In [23]:
def SinglePointCrossing(parent_one,parent_two):
    """
    По хорошему нужен более качественный генератор случайных чисел
    """
    point = np.random.randint(min(len(parent_one),len(parent_two)) - 1)
    return np.hstack([parent_one[:point],parent_two[point:]])

In [24]:
def Mutation(individual,probability = 0.3):
    """
    вероятность поменять ген
    """
    for i in range(len(individual)):
        if np.random.rand() > probability:
            individual[i] = (individual[i] + 1) % 2
    return individual

In [25]:
def f(x):
    return -(x**2)

In [26]:
a = -5
b = 5

In [84]:
IndNum = 10
population = [GrayСode(16) for i in range(IndNum)] # Это вот инициализация 

In [85]:
# Функция приспособленности
def MyFunc(x):
    return f(Decode(a,b,x).decode())

In [93]:
for i in range(10000):
    #print('=== STEP {} ==='.format(i))
    population = sorted(population,key=MyFunc,reverse=True) # reversed = True, когда ищем максимум
    # Хотим взять n самых крутых родителей
    to_produce = population[:4]
    # Продумать этот момент получше
    #print(population)
    first_children = Mutation(SinglePointCrossing(to_produce[0],to_produce[1]))
    #print(first_children)
    second_children = Mutation(SinglePointCrossing(to_produce[2],to_produce[3])) 
    #print(second_children)
    population = np.vstack([population,first_children,second_children])
    population = sorted(population,key=MyFunc,reverse=True)[:10] # оставляем 10 лучших особей

In [90]:
Decode(a,b,population[0]).decode()

-0.027085177159947627

In [94]:
for i in population:
    print(i, Decode(a,b,i).decode())

[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0] -7.629627368999081e-05
[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1] -0.00022888882106997244
[1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1] 0.00038148136844995406
[0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1] -0.0009918515579698806
[0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0] -0.002365184484389715
[0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0] -0.002517777031769697
[1 1 0 0 0 0 0 0 0 0 0 1 1 0 0 1] 0.0026703695791496784
[0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 1] -0.0026703695791496784
[1 1 0 0 0 0 0 0 0 0 0 1 1 0 1 1] 0.00282296212652966
[1 1 0 0 0 0 0 0 0 0 0 1 1 1 1 0] 0.0031281472212896233
