Цель - оптимизировать квадратичную функцию

Декодирование

In [118]:
# Вот это нужно
import numpy as np

#class GrayСode:
#    """
#    """
#    def __init__(self,BinLen=32):
#        self.BitString = np.random.randint(2, size=BinLen)

def GrayСode(BinLen=32):
    return np.random.randint(2, size=BinLen)

In [52]:
# Тоже нужно
def GrayToBinar(bit_string):
    """
    Правило перевода из кода Грея в позиционный код: каждый разряд в позиционном
    коде равен сумме по модулю два этого и всех старших разрядов в коде Грея
    """
    return [sum(bit_string[:i]) % 2 for i in range(len(bit_string),0,-1)][::-1]

In [109]:
# Нужно
def BinaryToInt(bit_string):
    """
    """
    return sum([int(x) * 2 ** y for x, y in zip(list(bit_string), range(len(bit_string) - 1, -1, -1))])

In [110]:
BinaryToInt([1, 0, 0, 1])

9

In [113]:
# Работает
class Decode:
    """
    Полный цикл декодирования: Грей -> двоичный -> целое -> нецелое
    """
    def __init__(self,a,b,bit_string):
        self.A = a
        self.B = b
        self.BitString = bit_string
        self.k = 2**len(bit_string) - 1 
        self.h = (b - a)/(self.k - 1)
    
    def decode(self):
        binary_srting = GrayToBinar(self.BitString)
        #print('binary: ',binary_srting)
        integer = BinaryToInt(binary_srting)
        #print('integer: ',integer)
        if integer == 0:
            return self.A
        elif integer == self.k:
            return self.B
        else:
            return ((self.A + (integer - 1)*self.h + (self.A+integer*self.h)))/2

In [115]:
Decode(-1,6,[0,0,1,1]).decode()

-0.25

In [ ]:
class GeneticBinar:
    """
    docstring
    """
    def __init__(self,GenNum=100,IndNum=10):
        """Constructor"""
        self.number_of_individuals_in_population = IndNum
        self.number_of_generation = GenNum
        self.population = []

Далее наивно делаем pipeline генетического алгоритма

In [124]:
def f(x):
    return -(x**2)

In [126]:
a = -5
b = 5

In [144]:
# step = 0
IndNum = 4
population = [GrayСode(4) for i in range(IndNum)] # Это вот инициализация 
population

[array([0, 1, 1, 1]),
 array([1, 1, 0, 0]),
 array([0, 0, 0, 1]),
 array([0, 0, 1, 0])]

In [145]:
for i in population:
    print(Decode(a,b,i).decode())

-1.7857142857142856
0.3571428571428572
-4.642857142857142
-3.2142857142857144


In [146]:
# Функция приспособленности
def MyFunc(x):
    return f(Decode(a,b,x).decode())

In [152]:
# Отбор родителей! Нужна функция приспособленности!
population = sorted(population,key=MyFunc,reverse=True)# reversed = True, когда ищем максимум
# Хотим взять n самых крутых родителей
to_produce = population[:2]
to_produce

[array([1, 1, 0, 0]), array([0, 1, 1, 1])]

In [ ]:
# Тут надо скрестить родителей из to_produce

In [134]:
# Тут случайно мутируем

In [ ]:
# Тут добавляем детей в поколение, сортируем его, выбираем самых лучших, смотрим условие